import express from 'express';
import { getNotifications, getUnreadCount, markRead, markAllRead } from '../controllers/notificationController.js';
import { protect } from '../middleware/auth.js';
const router = express.Router();
router.use(protect);
router.get('/', getNotifications);
router.get('/unread-count', getUnreadCount);
router.put('/mark-all-read', markAllRead);
router.put('/:id/read', markRead);
export default router;
